name: (CI) tap-bigquery

on:
  push:
    branches:
      - *

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        cache: poetry
    - run: poetry install
    - run: poetry run ruff
    - run: poetry run mypy
    - run: poetry run pytest
